### ISSUE TITLE
bad link in README.md

### ISSUE THREAD

**Issue by kpym** [VladimirMarkelov/rclc#1]
The [link to the documentation](https://github.com/VladimirMarkelov/rclc/blame/9085db0bc475127d4531bc4a850011e686833994/README.md#L51) in the README should be corrected : replace `docs.md` to `doc.md` :

```
Please, read the detailed [documentation here](doc.md).
```

**Comment by VladimirMarkelov** [comment]
Thank you for a good catch! Fixed
