### ISSUE TITLE
Roots

### ISSUE THREAD

**Issue by sergeevabc** [VladimirMarkelov/rclc#3]
I tried to calculate a few roots expressions from the [math article][1] such as `500×(1.06)⁹` by replacing
× with * and ⁹ with ^9, but `rclc` reported `ERROR: bitwise operator supports only integers`,
however `500*(1.06)^9` works with both Qalc and Kalker. So what's the way to achieve it here?

[1]: https://revisionmaths.com/gcse-maths-revision/number/percentages

**Comment by VladimirMarkelov** [comment]
Yes, I also sometimes run into the same trouble. It looks like my original idea is not good. It is time to improve it and then release stable 1.0.

At this moment, to raise to Nth power, one has to use `**`: `500*(1.06)**9`. But many people are used to `^` as a power operator. I can make `**` and `^` synonyms, and introduce another character for XOR bit-wise operation. The character `@` seems a good replacement for the current `^`.

**Comment by VladimirMarkelov** [comment]
The same pre-release: https://github.com/VladimirMarkelov/rclc/releases/tag/0.8.9-rc4 to test "^" for raising to power
